### ISSUE TITLE
Nothing constrains the wildtype DASM prediction

### ISSUE THREAD

**Issue by matsen** [matsengrp/netam#94]
Looking at some output of DASMs I started wondering what the DASM values for the wildtype AAs are. Then, thinking about the likelihood

![image](https://github.com/user-attachments/assets/ad2246a7-fa6a-4997-a763-0f335138cf26)

where

![image](https://github.com/user-attachments/assets/8e32c7ac-f089-4871-90f5-0fc6ecbbbec9)

we can see that the non WT AA doesn't appear. It also doesn't appear for branch length optimization.

![image](https://github.com/user-attachments/assets/ff0550e8-0b8e-4a70-8f86-2d0d6993ff6d)

## What to do?

1. We could reparameterize the model so that the prediction of WT is always equal to one. For example, we could divide by the WT value before outputting. (What would happen for ambiguous input sites?)
2. We could just set WT to be NaN for the end-user prediction function. This would mark these values as being dummy.

Option 1 would be slower and it seems like it could have some weird bad effect.

**Comment by matsen** [comment]
@willdumm I hope you don't mind but can I hand this off to you? When we evaluate a DASM using the `__call__` method, set the WT residues to nan. And have a little docstring linking to this issue saying that there is nothing constraining the WT value in the loss function, so we shouldn't make the mistake of interpreting it.

**Comment by willdumm** [comment]
Neither the Crepe class nor the Model class know whether they're a DNSM or DASM. I propose detecting this from within `Crepe.__call__` by reading the output_dim of the model, and setting wt positions to NaN if it's 20. Does that sound reasonable?

**Comment by matsen** [comment]
@willdumm Now I'm looking at this again when I'm doing benchmarking... and doesn't it make sense to set these WT values to 1? Isn't that exactly the way we have things set up in terms of eq:mutsel?
